<?php

function contactalter_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'contact_site_form') {
    $form['name']['#weight'] = -2;
    $form['firstname'] = array(
      '#type' => 'textfield',
      '#title' => t('Your firstname'),
      '#required' => FALSE,
      '#weight' => -1
    );

    //dpm($form);
  }
}

function contactalter_mail_alter(&$message) {
  if ($message['id'] == 'contact_page_mail') {

    $language = $message['language'];
    $params = $message['params'];

    if (isset($params['firstname'])) {
      $names = $params['firstname'] . " " . $params['name'];
      array_unshift($message['body'], $names);
    }
    /*
      $message['to'] = $more_receipient;
      $message['subject'] = $subject_overridden;
      $message['body'][0] = $msg_body;
      $message['body'][1] = $param_to_msg_body;
     */
  }
}
